### PR TITLE
Adding movem register list syntax

### PR DESCRIPTION
**Pull request by Dgdiniz**
Hi, this is a sugestion for the movem list syntax. A simple solution is to add the logic in the "analyzeInstruction" function, whose purpose is to change the instruction statement as needed. So if the current movem instruction has the list format, we transform the statement to the form supported by the assembler (the bitmask).
It's not the best solution but a simple one to add this feature.

### CODE REVIEW

**Comment by thar0x29a** [comment]
Hello. Thank you a lot for your contribution.
Unfortunately, I cannot accept it :/ 
The first problem is that this is a pull request for our master Branch. On Master we have Version 14 of Bass (with custom changes), which is outdated. The current development takes place in the 'devel' Branch, based on Version 17. This one will be released most likely as Version 18, or 1.0, or 1.18 .. Were not quite sure right now.

I have to admit, that currently it's difficult to see what 'we' do, or plan to do next. Please have a look at our wiki ([Bucket-List](https://github.com/ARM9/bass/wiki/Bucket-List)) to get in touch!

The second issue is that your code leaves the boundaries of a table assembler. It's a not platform independent feature but system/architecture specific. So, how to add it? 
Well. Since v15 bass has a clean architecture interface. I would say that we should extend the Table class with your code, and add it as an official, hardcoded, option. 

Since this is a process that needs to be documented anyway (with an example) I would offer my help on that one.

**Comment by Dgdiniz** [comment]
Hi, no problem. It's only a temporary workaround for someone who wants to use the register list syntax in v14 with Genesis arch while some other branch implements it in a more correct way. It's little annoying to use the current bitmask syntaxe with the "movem" instruction because the bits need to be reversed based on the operation.
I never used Bass v15-17 and seems that right now only v14 supports the Sega Genesis and the other architectures. I use v14 since the release but I'd change to a newer version if the other architectures are ported. 
Seems that the "devel" branch already has the other architectures. Is this branch based on v17, right? Is it simple to port the architecture files to v17 or something more complex has to be changed?

**Comment by thar0x29a** [comment]
Yes I know exactly how anoying it can be sometimes and it make sense to have this special case beeing included into an 'hardcoded' solution. 

Right now I ported all arch files over to the devel branch. Genesis should be included. However. It's not fertifyed that everything works. We have a test dir and my current task is to go over it and confirm one by one that it compiles, and generates the same output. 
Yes it is based on v17, the last one that came from near and hit the outside world. 
Porting the architecture can be easy, by just removing the C Stuff in it. In 99% of the cases thats all.

**Comment by Dgdiniz** [comment]
Hi, I tried to port the Mega Drive achitecture to the unmodified v17 released by Near and I could make it to assembly an old project I have here (made with v14), but it failed silently. No error was reported and nothing happened. 
So I compiled your "devel" branch, since you changed some code related to the architetures, an now I can see the error. In both tests the problem is related to the "dbra" instruction. I still don't know why this error is occurring, since the code is correct and working with v14. The error is:

`error: malformed expression: a d2 [unrecognized terminal]
project.asm:137:1: dbra d2,copy_char
bass: assembly failed`

If I remove all the lines with the "dbra" instructions from the project then the assembler can finish without any other errors.
Do you have any ideas?

**Comment by thar0x29a** [comment]
I noticed that something is still wrong there. Well, thats why its devel :/  Ill take a look at it on the next days. 
If you wish an more direct support feel free to add me on discord.

**Pull request closed without merging**
